import type { Metadata } from 'next'
import { Nunito, PT_Sans } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './components/theme-provider'
import { Toaster } from 'react-hot-toast'
import { Navigation } from './components/NavigationMenu'
import Footer from './components/Footer'

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['300', '400', '600', '800'],
})
const ptSans = PT_Sans({
  // Make sure the function name matches the imported name
  subsets: ['latin'],
  weight: ['400', '700'], // Choose the weights you need
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="se">
      <body className={`${nunito.className} ${ptSans.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange // Prevent transition on initial page load and theme change (re-enable with a delay) to avoid a flash of light and dark mode on initial load (remove if not important to you)
        >
          <Navigation />
          <main>{children}</main>
          <Toaster position="top-right" />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
